#!/bin/sh

distro() {
    . /etc/os-release

    os=${PRETTY_NAME:-Linux}
}

memory() {
    while IFS=: read -r key val; do
        val=${val%kB}

        case $key in
            MemTotal)
                mem_used=$((mem_used + val))
                mem_total=$val
            ;;

            Shmem)
                mem_used=$((mem_used + val))
            ;;

            MemFree|Buffers|Cached|SReclaimable)
                mem_used=$((mem_used - val))
            ;;
        esac
    done < /proc/meminfo

    memory="$((mem_used / 1024))MiB / $((mem_total / 1024))MiB"
}

uptime() {
    IFS=. read -r s _ < /proc/uptime

    d=$((s / 60 / 60 / 24))
    h=$((s / 60 / 60 % 24))
    m=$((s / 60 % 60))

    [ "$d" = 0 ] || uptime="${uptime}${d}d "
    [ "$h" = 0 ] || uptime="${uptime}${h}h "
    [ "$m" = 0 ] || uptime="${uptime}${m}m "
}

kernel() {
    read -r _ _ kernel _ < /proc/version
}

model() {
    read -r model < /sys/devices/virtual/dmi/id/product_version
}

hostname() {
    read -r hostname < /proc/sys/kernel/hostname
}

packages() {
    set -- /var/db/kiss/installed/*/
    packages=$#
}

main() {
    c0=[m
    c1=[34\;1m
    c2=[35\;1m
    c3=[37\;1m

    hostname
    distro
    model
    kernel
    uptime
    packages
    memory

    printf '%s\n' "\
${c1}    ___${c0}       ${c1}${USER}${c0}@${c1}${hostname}
${c1}   (${c3}.· ${c1}|${c0}      ${c2}os${c0}:     $os
${c1}   (${c2}<> ${c1}|${c0}      ${c2}host${c0}:   $model
${c1}  / ${c3}__  ${c1}\\${c0}     ${c2}kernel${c0}: $kernel
${c1} ( ${c3}/  \ ${c1}/|${c0}    ${c2}uptime${c0}: $uptime
${c2}_${c1}/\ ${c3}__)${c1}/${c2}_${c1})${c0}    ${c2}pkgs${c0}:   $packages
${c2}\/${c1}-____${c2}\/${c0}     ${c2}memory${c0}: $memory
"
}

main
