#!/bin/sh -e
#
# kiss-chroot: Enter a kiss chroot.

die() {
    printf '\033[31m!>\033[m %s\n' "$@" >&2
    exit 1
}

log() {
    printf '\033[32m=>\033[m %s\n' "$@"
}

clean() {
    log "Unmounting /dev, /proc and /sys from chroot."
    umount "$1/dev"  ||:
    umount "$1/proc" ||:
    umount "$1/sys"  ||:
}

main() {
    [ -z "$1" ]         && die "Need a path to KISS chroot."
    [ -d "$1" ]         || die "Given path doesn't exist."
    [ "$(id -u)" != 0 ] && die "Script needs to be run as root."

    trap 'clean "$1"' EXIT INT

    log "Mounting /dev, /proc and /sys from host."
    mountpoint -q "$1/dev"  || mount -o bind /dev "$1/dev"
    mountpoint -q "$1/proc" || mount -t proc proc "$1/proc"
    mountpoint -q "$1/sys"  || mount -t sysfs sys "$1/sys"

    log "Copying /etc/resolv.conf from host."
    cp /etc/resolv.conf "$1/etc"

    log "You may need to run 'update-ca-certificates' for SSL." \
        "You may need to run 'kiss update'." \
        "Entering chroot."

    chroot "$1" \
        /usr/bin/env -i \
            HOME="/root" \
            TERM="$TERM" \
            SHELL="/bin/sh" \
            USER="root" \
            CFLAGS="${CFLAGS:--march=x86-64 -mtune=generic}" \
            CXXFLAGS="${CXXFLAGS:--march=x86-64 -mtune=generic}" \
            MAKEFLAGS="$MAKEFLAGS" \
        /bin/sh -l
}

main "$@"
