#!/bin/sh -e
#
# kiss-orphans - List orphaned packages.

cd "$KISS_ROOT/var/db/kiss/installed/"

for pkg in *; do
    # Skip these packages.
    case $pkg in
        baseinit|baselayout|gcc|pkgconf|e2fsprogs|\
        make|busybox|ca-certificates|bzip2|grub)
                continue
        ;;
    esac

    grep -q "^$pkg$" ./*/depends || printf '%s\n' "$pkg"
done
